### ISSUE TITLE
Błąd CRC

### ISSUE THREAD

**Issue by kolankobulka** [Grycek/ChomikUploader#10]
Przy wysyłaniu plików rar, różnej wielkości (500MB - 3GB), nieważne ile razy i w jaki sposób, i z jakiego sprzętu plik jest uszkodzony. Po ściągnięciu z chomika, i próbie rozpakowania, wyświetla zawsze "nieoczekiwany koniec archiwum", przy teście rarem z lini komend, wyswietla błąd zawsze przy 99-100%, także wygląda jakby końcówki plików nie były przesyłane. Nie jest to pojedyńczy przypadek, wysłałem ponad 150GB różnych plików spakowanych, i wszystkie ten sam objaw... Da sie coś z tym zrobic? Dodam że używam na linuxie.

**Comment by mariuszrmw** [comment]
Dotyczy to wszystkich plików nagle ostatnie 2 bajty pliku nie są wysylane.

**Comment by Grycek** [comment]
Ostatnio mam dość mało czasu. Postaram się tym zająć, ale najwcześniej będę mógł to w weekend zrobić.

**Comment by kolankobulka** [comment]
W weekend mogę pomóc z testowaniem jakby co

**Comment by szafran81** [comment]
Potwierdzam. Każdy plik - tekstowe i binarki - skraca o 2 bajty.

**Comment by Grycek** [comment]
Na razie wprowadziłem rozwiązanie tymczasowe. Zobaczymy jak zadziała.
Poprawiona wersja:
https://github.com/Grycek/ChomikUploader/blob/master/dist/chomikUploader-0.5.1.2.zip

**Comment by kolankobulka** [comment]
THX. Działa perfekto przy mniejszych plikach. Poźniej potestuje jeszcze te większe 1GB+

**Comment by kolankobulka** [comment]
Jednak nie dobrze. Przy wysyłaniu kilkudziesięciu plików po 500MB, za każdym razem jest  5-7 plików wysłanych z błędami. Po porównaniu plików, błędy w plikach występują losowo.

**Comment by mariuszrmw** [comment]
Potwierdzam nadal brakuje 2 ostatnich bajtów w plikach. Jest ich mniej ale nadal są :(
Problem jest zarówno w małych jak i wielkich plikach.
testowałem na plikach od 200KB do 5GB

**Comment by kolankobulka** [comment]
Problem chyba nie do przeskoczenia z tymi błędami. Co ciekawe pliki MKV pomimo że z błędami odtwarzają się bezbłędnie

**Comment by Grycek** [comment]
Problemem jest to, że chomikuj zmienił protokół w chomikboksie i jeszcze nie odkryłem jak dokładnie działa.
Czy błędy występuję w środku plików? Czy zawsze są to 2 bajty?

**Comment by mariuszrmw** [comment]
Podczas wysyłania plików błąd zawsze jest na końcu pliku. Brak 2 bajtów.
Z tego co zauważyłem jeszcze nie wszystkie serwery mają nowy protokół bo małe pliki na stare serwery idą bez błędów. Na nowe już niestety wszystkie są uszkodzone.
Czasami błędy są w środku ale to się dzieje podczas zrywania wysyłania.

**Comment by Freewolny** [comment]
Grycek: przerzuć się na PyCURL i wrzucaj pliki używając tego. Sądzę, że pomoże.

**Comment by Grycek** [comment]
Problemem nie jest biblioteka do wysyłania plików, a rozszyfrowanie protokołu, który chomikuj używa.
Wprowadziłem drobne zmiany do programu. Wysyłałem kilkadziesiąt dużych i mały plików i działało bez problemu. Ale może to kwestia szczęścia.
https://github.com/Grycek/ChomikUploader/blob/master/dist/chomikUploader-0.5.3.zip

Problemem jest to, że chomikbox inaczej przelicza rozmiar pliku. I praktycznie zawsze jest to różnica dwóch bajtó (w moim przypadku mam dwa bajty za dużo w porównaniu do chomikboxa). Nie wiem jak rozwiązać ten problem. Wydaje mi się, że dokładnie imituję protokół chomikboxa.

**Comment by Freewolny** [comment]
Wydaje mi się, że robisz to kompletnie źle. Samo wysyłanie pliku to jest
standardowa formatka protokołu HTTP. Napisałem swój skrypt i działa bez
zarzutu. Spróbuj użyć biblioteki Requests: HTTP for Humans.

pon., 15.06.2015 o 11:29 użytkownik Grycek <notifications@github.com>
napisał:
