### ISSUE TITLE
Bad token

### ISSUE THREAD

**Issue by czikokolo** [Grycek/ChomikUploader#11]
Przy zakończeniu uploadu na jedym koncie i rozpoczęciu uploadu na drugie konto, żadne pliki nie chcą się uploadować.

BLAD(nieudane wysylanie):
Bad token

**Comment by Grycek** [comment]
Prawdopodobnie po poprzednim koncie został plik notuploaded.txt, w którym zapisane są informacje, które pliki nie udało się wysłać i co zrobić, żeby wznowić to wysyłanie.

Logując się na drugie konto program próbuje wznowić wysyłanie nieudanych plików z poprzedniego konta, co prowadzi do błędu.

Szybkie rozwiązanie - po wysłaniu plikóœ z pierwszego konta usuń pliki notuploaded.txt i uploaded.txt z katalogu gdzie odpalałeś program.
