### ISSUE TITLE
Polskie znaki i znaki specjalne

### ISSUE THREAD

**Issue by replay111** [Grycek/ChomikUploader#15]
Cześć,

a dałoby się zrobić tak, żeby podczas wrzucania plików, skrypt nie reagował na polskie znaki albo znaki specjalne? Mam np plik: "pod górę.txt" i jest błąd podczas wgrywania. Podobnie jest jak mam pliki np jpg, które w nazwie mają "IMG123123 - kopia.jpg" - czyli sekwencja " - " jest już problemem.
W ruby jest taka fajna opcja: ActiveSupport::Inflector.transliterate("pod górę.txt") -> zwróci "pod gore.txt" - jest to już lepsze wyjście niż ciągły błąd :D

**Comment by KarwaszTwarz** [comment]
U mnie nie ma takich problemów. Jedynie z plikami, których nazwy zawierają apostrofy lub znaki spoza zainstalowanych języków.

**Comment by replay111** [comment]
@KarwaszTwarz A na jakim sysie odpalasz?

**Comment by KarwaszTwarz** [comment]
@replay111 Debian 8.

**Comment by mruczek** [comment]
Też mam taki problem, testowałem na systemie Debian 8 i Arch Linux

**Comment by Grycek** [comment]
Ja w sumie też miewam ten problem. Jak będę miał wolny czas to się temu przyjrzę.

**Comment by replay111** [comment]
Ja używam akurat Centos 7...

**Comment by Grycek** [comment]
Sprawdźcie teraz.
