### ISSUE TITLE
Problems with codification.

### ISSUE THREAD

**Issue by israelgf** [Grycek/ChomikUploader#16]
Hello,

When I try upload files in mi native language "spanish" Show me these errors by console. How can I solve these problems when uploading files with special characters "aéíóúñÁÉÍÓÚÑ¿¡"?

'utf8' codec can't decode byte 0xe9 in position 13: invalid continuation byte
Blad. Nie wyslano katalogu:  /media/acd/Biblioteca/Películas/Alicia a través del espejo (2016) [6.5]
'ascii' codec can't decode byte 0xe9 in position 13: ordinal not in range(128)
'utf8' codec can't decode byte 0xf3 in position 16: invalid continuation byte
Blad. Nie wyslano katalogu:  /media/acd/Biblioteca/Películas/Alien resurrección (1997) [5.8]
'ascii' codec can't decode byte 0xf3 in position 16: ordinal not in range(128)

I take the opportunity to thank you for your great work.
Regards.

**Comment by Grycek** [comment]
Thanks. I've tried to update the code to handle those cases.
Could you try it?

**Comment by israelgf** [comment]
Hello,

Many thanks but after installing the new version chomikUploader-0.5.4.3.zip I still have the same problem.

----------------------------------------------------------------------------------------------------------

> Logowanie
> Logowanie
> Logowanie
> Wznawianie nieudanych transferow
> Zakonczono probe wznawiania transferow
> 
> Zmiana katalogow
> Wznawianie nieudanych transferow
> Zakonczono probe wznawiania transferow
> 
> Zmiana katalogow
> 'utf8' codec can't decode byte 0xe9 in position 13: invalid continuation byte
> Blad. Nie wyslano katalogu:  /media/acd/Biblioteca/Películas/Alicia a través del espejo (2016) [6.5]
> 'ascii' codec can't decode byte 0xe9 in position 13: ordinal not in range(128)
> 'utf8' codec can't decode byte 0xf3 in position 16: invalid continuation byte
> Blad. Nie wyslano katalogu:  /media/acd/Biblioteca/Películas/Alien resurrección (1997) [5.8]
> 'ascii' codec can't decode byte 0xf3 in position 16: ordinal not in range(128)

-------------------------------------------------------------------------------------------------

If it helps, I have installed the following locales in the system.

C.UTF-8                                                        
es_ES.UTF-8                                                  
es_ES@euro  

The user has configured:

LANG=es_ES@euro

More information about the system:

Linux SRVDebian001 4.4.35-1-pve #1 SMP Fri Dec 9 11:09:55 CET 2016 x86_64 GNU/Linux

Thank you for your help.

**Comment by israelgf** [comment]
Hello,

I have changed the locale to utf-8 and now it works without problems.

Thank you very much.
