### ISSUE TITLE
Skrypt przestral dzialac

### ISSUE THREAD

**Issue by arcaine2** [Grycek/ChomikUploader#21]
Skrypt przestal dzialac, nie zwraca nawet zadnego bledu.

**Comment by KarwaszTwarz** [comment]
Czasami wyrzuci time out, ale poza tym działa :)

**Comment by arcaine2** [comment]
Hmm, rzeczywiscie. Wersja ktora mam na dysku nie dziala. Pobralem jeszcze raz calosc na nowo i sie laczy. Widac jakies przeoczenie z mojej strony. Temat mozna uznac za zamkniety.
