### ISSUE TITLE
Logowanie, timed out

### ISSUE THREAD

**Issue by SanZamoyski** [Grycek/ChomikUploader#22]
Cześć!

Używam tego skryptu od lat i nigdy nie sprawiał mi problemów (siedzi sobie na serwerze z torrentami i od czasu do czasu zrzuca rzeczy na chomik). Ostatnio dostaję ciągle informację "timed out". Na chomiku się coś zmieniło czy to przejściowe?

Pozdrawiam!

**Comment by SanZamoyski** [comment]
Czasem wysyła. 

```
Logowanie
Zmiana katalogow
Uploadowanie
Blad:  timed out
Blad. Plik nie zostal wyslany
```

**Comment by KarwaszTwarz** [comment]
Problem znany od miesięcy. Czasami nie chce się nawet zalogować.

**Comment by SanZamoyski** [comment]
@Barabasz
dzięki za info!
